-- Saved study plans (generated by study_planner agent)

CREATE TABLE IF NOT EXISTS study_plans (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id     UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  config        JSONB NOT NULL,
  plan          JSONB NOT NULL,
  agent_job_id  UUID REFERENCES agent_jobs(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE study_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "study_plans_select" ON study_plans
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "study_plans_insert" ON study_plans
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "study_plans_delete" ON study_plans
  FOR DELETE USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_study_plans_user_created
  ON study_plans(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_study_plans_user_course
  ON study_plans(user_id, course_id);
